### ISSUE TITLE
Crawlers out of memory: Kill child process

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-framework#42]
I don't know if you experience that too. But I have a lot of docker cgroup out of memory issues resulting into the killing of child process with splash crawler. Don't know if there is an actual negative impact.
I did set `--memory=2G` to `--memory=3G` at
`screen -S "Docker_Splash" -X screen -t "docker_splash:$port_number" bash -c 'sudo docker run -d -p '$port_number':8050 --restart=always --cpus=1 --memory=3G -v '$f':/etc/splash/proxy-profiles/ --net="bridge" scrapinghub/splash --maxrss '$u'; read x'` in `bin/torcrawler/launch_splash_crawler.sh ` and that seems to have resolved this.
I am running 6 crawlers concurrently.
Don't know if this should be changed as a standard setting in the source.

**Comment by Terrtia** [comment]
Hi @certrik !

The RAM used after a Splash request isn't freed, so the overall consumption is growing until reaching exhaustion.

The only way to solve this issue is to restart a Splash instance when it use all your configured memory.
To solve this issue, we are using ``--restart=always`` option to restart the docker when a Splash instance fail (segfault or memory exhaustion).

By default, we check if Splash is available before crawling a domain. However, if a Splash instance restart when we are crawling a domain we were losing some urls.

I modified the error handler in the scrapy-splash script (abfad615817c821ab7098d8f689937c56dd269f8). The crawler wait and retry for each url if the Splash instance is unreachable.
