### ISSUE TITLE
Stops after one hour

### ISSUE THREAD

**Issue by mouloren** [ail-project/ail-framework#47]
When I start AIL after about an hour it stops. The command executed is the ./LAUNCH.sh within the venv. 
The interface works but the feeders and pystemon do not report anything to the console. Is there any way to make them persistent?

Thanks and greetings

**Comment by certrik** [comment]
It is odd that it stops after one hour.
For me ail-framework works with the pystemon feeder, if the path to pystemon is set correctly in `configs/core.cfg` and the pystemon directory resides in same directory as the ail-framework directory, so that both directories are on the same level. You can have a look into `/bin/LAUNCH.sh`. The `./bin/LAUNCH -f` starts pystemon from `../../pystemon/pystemon.py` . I use pystemon from the official repo at https://github.com/cvandeplas/pystemon . Of yourse you have to configure `pystemon.yaml` to your needs. Also be aware that pastebin has changed a lot regarding scraping without an enterprise license.
If everything is set correctly you should be able to start the ail-framework from without the virtual env from the working directory `/ail-framework` with `./bin/LAUNCH.sh -l` and start the pystemon feeder automatically with `./bin/LAUNCH.sh -f`.
